#!/bin/bash

# KERNEL=linux-yocto-3.14/arch/x86/boot/bzImage
# KERNEL=linux-yocto-3.14/core-image-lsb-sdk-qemux86.ext3

source /scratch/opt/environment-setup-i586-poky-linux 

# qemu-system-i386 -gdb tcp::5618 -S -nographic -kernel $KERNEL             \
#        -drive file=core-image-lsb-sdk-qemux86.ext3,if=virtio -enable-kvm \
#        -net none -usb -localtime --no-reboot                             \
#        --append "root=/dev/vda rw console=ttyS0 debug"

#qemu-system-i386 -gdb tcp::5618 -S -nographic -kernel bzImage-qemux86.bin -drive file=core-image-lsb-sdk-qemux86.ext3,if=virtio -enable-kvm -net none -usb -localtime --no-reboot --append "root=/dev/vda rw console=ttyS0 debug"

qemu-system-i386 -gdb tcp::5618 -S -nographic -kernel arch/i386/boot/bzImage -hda core-image-lsb-sdk-qemux86.ext3 -enable-kvm -net none -usb -localtime --no-reboot --append "root=/dev/hda rw console=ttyS0 debug"

